databaseGenerator:
  url: jdbc:mysql://localhost:3306/data
  userName: root
  password: qwe123456
  author: kaki
  tables: product_textile_exchange_standard,product_textile_exchange_standard_mapping,product_category_global_standard_one_standard
  packageConfig:
    javaTargetProject: /Users/kaki/IdeaProjects/carbon-mybatis-generator/carbon-mybatis-generator-plugin/src/test/java/com/carbon
    xmlTargetProject: /Users/kaki/IdeaProjects/carbon-mybatis-generator/carbon-mybatis-generator-plugin/src/test/java/resources/mapper